volume = 1.0
maxPlayCont = 8
spatial = true
sampleRate = 44100
useYoutubeDownloader = true
relayServerURL = "https://raw.githubusercontent.com/TeamFelnull/IamMusicPlayer/master/relay_server.json"
lavaPlayerNativesURL = "https://raw.githubusercontent.com/Mod-Sauce/test_lavaplayer_IMP/refs/heads/main/lavaplayer/natives_link.json"
hashBaseUrl = "https://raw.githubusercontent.com/Mod-Sauce/test_lavaplayer_IMP/refs/heads/main/lavaplayer"
IMPRFolder = "iammusicplayerrenewed"
lavaNativesFolder = "lavaplayer_natives"
hideDisplaySprite = false
hideDecorativeAntenna = false
tryUseGitee = false
maxWaitTime = 10000
retryTime = 3000
dropItemRing = true
soundPhysicsRemasteredIntegration = true
touhouLittleMaidIntegration = true
patchouliIntegration = true
showMusicLines = false
showSpeakerRange = false
configVersion = "1"
enableNetease = true
withTransName = true
neteaseCookie = ""
enableMusicInfoHUD = true
hudX = 10
hudY = 10
createIntegration = true
